### PR TITLE
Shared intro added to cover 'why pony?' for all languages

### PR DESCRIPTION
**Pull request by cquinn**
Combining intro material from Ivo's C# chapter as well as my (in progress) Java chapter.

It seems nicer to describe Pony's general language features in one place so that we don't have to re-summarize them in each chapter.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
@cquinn Thanks Carl! I'm going to merge this and then update. In the future, please keep lines below 80 columns. I thought I had included that in contributing.md but apparently I didn't because, every time I do a contributing.md, I leave that out.

**Comment by cquinn** [comment]
You did have that note regarding 80 col limit in the contributing doc, but I didn't understand why so I had asked it in another email thread. It seems harder (in my editor, Sublime) to work with paragraphs that have hard breaks than just letting the text editor soft-wrap at 80. Maybe other editors are easier, and I'm going to give the GitBook Editor a try.

**Comment by SeanTAllen** [comment]
There's the autowrap plugin for Sublime.

**Comment by sylvanc** [comment]
Does text/docs need to be 80 col hard broken? For code, it allows consistent formatting in two columns on a laptop, and consistent results when copying/pasting code. Code doesn't autowrap well, as line breaks appear in strange places. But text seems to do ok - not code snippets, of course, but the rest.

But I may be missing something important?

**Comment by jemc** [comment]
Wasn't going to speak up, but since @sylvanc did, I also think that hard-wrapping markdown content is an unnecessary burden.  Most (all?) major editors support a soft-wrap view, and the ultimate renderer of the content (in GitHub or otherwise) is just going to unwrap your hard-wraps and make the text flow to the width of the container.

**Comment by SeanTAllen** [comment]
¯_(ツ)_/¯ ok then. Feel free to update all the relevant contributing docs and I'll turn on softwrap for .md and .asciidoc documents.

**Comment by jemc** [comment]
@sylvanc - if you give a final nod of approval, I'll go ahead and make those changes.

**Comment by sylvanc** [comment]
Yeah, let's go for it. I think it is a bit more "relaxed" for contributors, without making things harder for anyone.

**Comment by SeanTAllen** [comment]
I've been playing around with this "relaxed" softwrap thing and its kind of a mess when it comes to reading. For every editor I try, I have to resize my window to get a decent reading experience. There's a limit to the number of columns a person can easily read before it becomes problematic. With softwrap and a standard 15" macbook pro, that is way less than window size which is what editors seem to default to. I can see where there is a slight bit of convenience on the creation side for softwrap but for me at least it comes at a larger pain for reading. 

I've found an emacs extension I can use when I'm in emacs to get softwrap at a sane column size but all in all, I find this problematic. Having a fixed maximum for column size makes reading easier in my mind. Maybe everyone else has solved this problem already and I never dealt with it because I never liked softwrap for this reason, or maybe everyone is doing something else. So far though playing around with this has been frustrating and difficult with default from less, sublime, emacs and vim.

**Comment by sylvanc** [comment]
Sublime:

```
View->Word Wrap
View->Word Wrap Column->80
```

vim:

```
:set wrap
:set columns=84 // to leave space for :set num
```

emacs/spacemacs:

http://emacs.stackexchange.com/questions/10798/if-longlines-mode-is-removed-in-new-emacs-how-can-i-soft-wrap-the-line-around-t

**Comment by SeanTAllen** [comment]
Set those. Don't like the experience. Maybe I'll get used to it.

**Comment by SeanTAllen** [comment]
FYI: the rust book appears to be capped at around 80 lines per file.

I also tried out softwrap and the impact on git diffs. Unfortunately git highlights changed lines which was somewhat annoying previously with docs but with softwrap because really problematic. This isn't a deal breaker but it will make diffs harder to parse, particularly in content on long paragraphs (as our new linebreak is a paragraph).

**Comment by sylvanc** [comment]
That may not be a deal breaker, but it's certainly a deal questioner.

**Comment by jemc** [comment]
Actually, when I went through and unwrapped all of these docs by hand, I found quite a few that were mis-wrapped at >80 chars, leading to a really bad reading experience on my end.

```
For example, many lines were mis-wrapped at greater than 80 characters but
because
my editor was wrapping those lines to at exactly 80 characters it led to a
reading
experience that was broken up and horrid.
```

Also, there was a mixture of lines that were hard-wrapped with a trailing space and lines that weren't.  Again, in an editor that is configured to soft-wrap all markdown (as mine will remain for my other projects), the trailing space can also lead to "double-wrap" like in the example above.

Expecting people to maintain hard line breaks in the right places when writing docs is an unnecessary burden on them, and will lead to fewer people wanting to contribute to docs.

> I also tried out softwrap and the impact on git diffs. Unfortunately git highlights changed lines which was somewhat annoying previously with docs but with softwrap because really problematic. This isn't a deal breaker but it will make diffs harder to parse, particularly in content on long paragraphs (as our new linebreak is a paragraph).

GitHub still highlights the specific words that were changed, in a darker color than the lines that were changed, as it does for all diffs.  Anyway, I find all the extra changes in hard line breaks in the diff more distracting than diffs that only differ in actual content.

**Comment by SeanTAllen** [comment]
I don't like the experience but in the end. ¯_(ツ)_/¯. I'm going to work on standard library docs for a while and not have to worry about it.

**Comment by cquinn** [comment]
I had the same experience as Joe did with the hard wrapping. Many lines
ended up breaking at the wrong place and leaving orphans on the following
line (in Sublime with the plugins). And after editing mid-paragraph, I
would have to manually invoke the wrap-paragraph command which didn't
always work.

Soft wrapping _seems_ to be the simplest and least troublesome, but I have
yet to try and read long-line diffs.

**Pull request merged**
